### ISSUE TITLE
Add basic configuration and info files

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mikescor#4]
* [x] `README.md`, stating your project title, styled with Markdown
* [x] `LICENSE` file. Find template for it in plain text or Markdown format. You may use MIT licence for simplicity
* [x] `.gitattributes`. Find some template for your repo on github
* [x] `.gitignore`. Find typical template for your language

**Comment by mikescor** [comment]
Done!
