### ISSUE TITLE
Learn pythonic stuff

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mikescor#7]
* [x] PEP8 (common conventions of writing and organizing code in the pythonic world)
* [x] PEP20 (Zen Of Python)
```python
import this
```
* [x] linters: flake8, pyflakes
* [x] virtualenv
  * [x] pyenv (install one locally using pyenv-installer, enable pyenv-virtualenv as well)
* [x] zsh (install and enable this shell in your machine)
  * [x] install oh-my-zsh framework to configure nice and useful terminal environment

**Comment by mikescor** [comment]
Done!
